# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Klakk.Klakk
PackageVersion: 1.4.1
InstallerType: inno
Scope: user
ProductCode: '{398236E7-8E2E-4998-934F-5E54AFA110E1}_is1'
AppsAndFeaturesEntries:
  - DisplayName: Klakk 1.4.1
    Publisher: Klakk
    DisplayVersion: 1.4.1
    ProductCode: '{398236E7-8E2E-4998-934F-5E54AFA110E1}_is1'
ReleaseDate: '2026-10-07'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Klakk'
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.tryklakk.com/Klakk-1.4.1-Windows-Setup.exe
    InstallerSha256: 7A598CC3D3EA7236F377D7281A68A25A799C4F1772DE9CE2A857D4C7658DF454
  - Architecture: arm64
    InstallerUrl: https://downloads.tryklakk.com/Klakk-1.4.1-Windows-Setup.exe
    InstallerSha256: 7A598CC3D3EA7236F377D7281A68A25A799C4F1772DE9CE2A857D4C7658DF454
ManifestType: installer
ManifestVersion: 1.12.0
